name: Build Native App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux
            arch: x86_64
            bundle_paths: |
              target/release/bundle/deb/Intear Wallet_0.1.0_amd64.deb
              target/release/bundle/rpm/Intear Wallet-0.1.0-1.x86_64.rpm
              target/release/bundle/appimage/Intear Wallet_0.1.0_amd64.AppImage
          - os: ubuntu-24.04-arm
            platform: linux
            arch: aarch64
            bundle_paths: |
              target/release/bundle/deb/Intear Wallet_0.1.0_arm64.deb
              target/release/bundle/rpm/Intear Wallet-0.1.0-1.aarch64.rpm
              target/release/bundle/appimage/Intear Wallet_0.1.0_aarch64.AppImage
          - os: windows-latest
            platform: windows
            arch: x86_64
            bundle_paths: |
              target/release/bundle/msi/Intear Wallet_0.1.0_x64_en-US.msi
              target/release/bundle/nsis/Intear Wallet_0.1.0_x64-setup.exe
          - os: macos-15
            platform: macos
            arch: aarch64-and-x86_64
            bundle_paths: |
              target/release/bundle/dmg/Intear Wallet_0.1.0_aarch64.dmg
              target/x86_64-apple-darwin/release/bundle/dmg/Intear Wallet_0.1.0_x64.dmg
          - os: ubuntu-24.04
            platform: android
            bundle_paths: |
              src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
              src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.prod .env

      - name: Set up signing for Android
        if: matrix.platform == 'android'
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Set up signing for macOS
        if: matrix.platform == 'macos'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        run: |
          printf "%s" "$APPLE_API_KEY_BASE64" | base64 --decode > ~/AuthKey.p8
          printf "%s" "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain
          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
          echo "Certificate imported."

      - name: Setup mold (Linux and Android)
        if: matrix.platform == 'linux' || matrix.platform == 'android'
        uses: rui314/setup-mold@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-01-27
          components: rust-src, cargo, rust-std, rustc

      - name: Install Tauri system dependencies (Linux)
        if: matrix.platform == 'linux' || matrix.platform == 'android'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libayatana-appindicator3-dev \
            libwebkit2gtk-4.1-0=2.50.4-0 \
            libwebkit2gtk-4.1-dev=2.50.4-0 \
            libjavascriptcoregtk-4.1-0=2.50.4-0 \
            libjavascriptcoregtk-4.1-dev=2.50.4-0 \
            gir1.2-javascriptcoregtk-4.1=2.50.4-0 \
            gir1.2-webkit2-4.1=2.50.4-0 \
            librsvg2-dev \
            libusb-1.0-0-dev \
            patchelf \
            build-essential \
            xdg-utils

      - name: Install Tauri system dependencies (macOS)
        if: matrix.platform == 'macos'
        run: |
          brew install pango jpeg librsvg llvm
          rustup target add x86_64-apple-darwin
          echo "CC_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV

      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v3

      - name: Setup Java JDK
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Cache cargo-installed binaries
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-${{ matrix.arch || 'universal' }}-cargo-tauri-bin-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch || 'universal' }}-cargo-tauri-bin-

      - name: Install build tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install patch-crate cargo-leptos tauri-cli --debug --locked --force

      - name: Install npm dependencies
        run: npm install

      - name: Install Tailwind CLI
        run: npm install -g @tailwindcss/cli@4.1.8

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Add Android targets
        if: matrix.platform == 'android'
        run: |
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi
          rustup target add i686-linux-android
          rustup target add x86_64-linux-android

      - name: Apply patches
        run: cargo patch-crate

      - name: Build Tauri app
        if: matrix.platform != 'macos'
        uses: tauri-apps/tauri-action@a5e8d02eebede9840d3c77437e8624c8f2836732
        with:
          tauriScript: cargo tauri
          mobile: ${{ matrix.platform == 'android' && 'android' || '' }}
        env:
          USE_ALTERNATIVE_WASM_PROTOCOL: ${{ matrix.platform == 'android' && '' || 'true' }}

      - name: Build macOS app
        if: matrix.platform == 'macos'
        uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: cargo tauri
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ env.CERT_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_PATH: ~/AuthKey.p8
        env:
          USE_ALTERNATIVE_WASM_PROTOCOL: "true"

      - name: Build macOS app (x86)
        if: matrix.platform == 'macos'
        uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: cargo tauri
          args: "--target x86_64-apple-darwin"
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ env.CERT_ID }}
        env:
          USE_ALTERNATIVE_WASM_PROTOCOL: "true"

      - name: Upload Tauri artifacts
        uses: actions/upload-artifact@v4
        with:
          name: intear-wallet-app-${{ matrix.platform }}-${{ matrix.arch || 'universal' }}
          path: |
            ${{ matrix.bundle_paths }}
